### ISSUE TITLE
Reset password email causes internal server error

### ISSUE THREAD

**Issue by NicholasCF** [nussucommit/takoyaki#533]
Unable to send password recovery email due to the error

Logs:
---
```
2020-09-16T14:05:58.660737+00:00 app[web.1]: Content-Transfer-Encoding: 7bit
2020-09-16T14:05:58.660737+00:00 app[web.1]: 
2020-09-16T14:05:58.660738+00:00 app[web.1]: <p>Hello nicholas.fernando@u.nus.edu!</p>
2020-09-16T14:05:58.660738+00:00 app[web.1]: 
2020-09-16T14:05:58.660739+00:00 app[web.1]: <p>Someone has requested a link to change your password. You can do this through the link below.</p>
2020-09-16T14:05:58.660740+00:00 app[web.1]: 
2020-09-16T14:05:58.660741+00:00 app[web.1]: <p><a href="http://duty.nussucommit.com/users/password/edit?reset_password_token=vZQrap1oJcSDi_sN7Kzj">Change my password</a></p>
2020-09-16T14:05:58.660741+00:00 app[web.1]: 
2020-09-16T14:05:58.660742+00:00 app[web.1]: <p>If you didn't request this, please ignore this email.</p>
2020-09-16T14:05:58.660742+00:00 app[web.1]: <p>Your password won't change until you access the link above and create a new one.</p>
2020-09-16T14:05:58.660743+00:00 app[web.1]: 
2020-09-16T14:05:58.660744+00:00 app[web.1]: I, [2020-09-16T14:05:58.655703 #4]  INFO -- : [a6d3c433-2e99-478e-8deb-88fc530dd146] Completed 500 Internal Server Error in 840ms (ActiveRecord: 8.8ms)
2020-09-16T14:05:58.661170+00:00 app[web.1]: F, [2020-09-16T14:05:58.661015 #4] FATAL -- : [a6d3c433-2e99-478e-8deb-88fc530dd146]
2020-09-16T14:05:58.661233+00:00 app[web.1]: F, [2020-09-16T14:05:58.661166 #4] FATAL -- : [a6d3c433-2e99-478e-8deb-88fc530dd146] Mailgun::CommunicationError (400 Bad Request: 'from' parameter is not a valid address. please check documentation):
2020-09-16T14:05:58.661297+00:00 app[web.1]: F, [2020-09-16T14:05:58.661236 #4] FATAL -- : [a6d3c433-2e99-478e-8deb-88fc530dd146]
2020-09-16T14:05:58.661419+00:00 app[web.1]: F, [2020-09-16T14:05:58.661334 #4] FATAL -- : [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mailgun-ruby-1.2.0/lib/mailgun/client.rb:107:in `rescue in post'
2020-09-16T14:05:58.661420+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mailgun-ruby-1.2.0/lib/mailgun/client.rb:103:in `post'
2020-09-16T14:05:58.661421+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mailgun-ruby-1.2.0/lib/mailgun/client.rb:87:in `send_message'
2020-09-16T14:05:58.661422+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mailgun-ruby-1.2.0/lib/railgun/mailer.rb:49:in `deliver!'
2020-09-16T14:05:58.661422+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
2020-09-16T14:05:58.661423+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
2020-09-16T14:05:58.661423+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:560:in `block in deliver_mail'
2020-09-16T14:05:58.661424+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
2020-09-16T14:05:58.661424+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
2020-09-16T14:05:58.661425+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
2020-09-16T14:05:58.661425+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:558:in `deliver_mail'
2020-09-16T14:05:58.661426+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
2020-09-16T14:05:58.661427+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
2020-09-16T14:05:58.661427+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
2020-09-16T14:05:58.661428+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
2020-09-16T14:05:58.661428+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/models/authenticatable.rb:199:in `send_devise_notification'
2020-09-16T14:05:58.661429+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/models/recoverable.rb:99:in `send_reset_password_instructions_notification'
2020-09-16T14:05:58.661430+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/models/recoverable.rb:52:in `send_reset_password_instructions'
2020-09-16T14:05:58.661430+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/models/recoverable.rb:136:in `send_reset_password_instructions'
2020-09-16T14:05:58.661431+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/app/controllers/devise/passwords_controller.rb:15:in `create'
2020-09-16T14:05:58.661431+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2020-09-16T14:05:58.661432+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
2020-09-16T14:05:58.661432+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
2020-09-16T14:05:58.661433+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
2020-09-16T14:05:58.661433+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
2020-09-16T14:05:58.661434+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
2020-09-16T14:05:58.661435+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
2020-09-16T14:05:58.661439+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
2020-09-16T14:05:58.661440+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
2020-09-16T14:05:58.661440+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
2020-09-16T14:05:58.661441+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
2020-09-16T14:05:58.661442+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
2020-09-16T14:05:58.661442+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
2020-09-16T14:05:58.661442+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
2020-09-16T14:05:58.661443+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
2020-09-16T14:05:58.661443+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
2020-09-16T14:05:58.661444+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-1.1.4/lib/mini_profiler/profiling_methods.rb:78:in `block in profile_method'
2020-09-16T14:05:58.661444+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
2020-09-16T14:05:58.661445+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
2020-09-16T14:05:58.661445+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
2020-09-16T14:05:58.661446+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
2020-09-16T14:05:58.661446+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
2020-09-16T14:05:58.661447+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
2020-09-16T14:05:58.661447+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
2020-09-16T14:05:58.661448+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
2020-09-16T14:05:58.661448+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
2020-09-16T14:05:58.661449+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
2020-09-16T14:05:58.661449+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/browser_details-0.0.6/lib/browser_details.rb:59:in `call'
2020-09-16T14:05:58.661450+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
2020-09-16T14:05:58.661450+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
2020-09-16T14:05:58.661451+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
2020-09-16T14:05:58.661451+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/tempfile_reaper.rb:17:in `call'
2020-09-16T14:05:58.661452+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/etag.rb:27:in `call'
2020-09-16T14:05:58.661452+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/conditional_get.rb:40:in `call'
2020-09-16T14:05:58.661453+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
2020-09-16T14:05:58.661453+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2020-09-16T14:05:58.661459+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:269:in `context'
2020-09-16T14:05:58.661459+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'
2020-09-16T14:05:58.661460+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
2020-09-16T14:05:58.661460+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
2020-09-16T14:05:58.661461+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
2020-09-16T14:05:58.661461+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2020-09-16T14:05:58.661462+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
2020-09-16T14:05:58.661462+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2020-09-16T14:05:58.661463+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
2020-09-16T14:05:58.661463+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
2020-09-16T14:05:58.661464+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
2020-09-16T14:05:58.661465+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
2020-09-16T14:05:58.661465+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
2020-09-16T14:05:58.661465+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
2020-09-16T14:05:58.661466+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2020-09-16T14:05:58.661466+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
2020-09-16T14:05:58.661467+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
2020-09-16T14:05:58.661482+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
2020-09-16T14:05:58.661483+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2020-09-16T14:05:58.661483+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
2020-09-16T14:05:58.661485+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
2020-09-16T14:05:58.661485+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
2020-09-16T14:05:58.661486+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/rack-mini-profiler-1.1.4/lib/mini_profiler/profiler.rb:184:in `call'
2020-09-16T14:05:58.661486+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
2020-09-16T14:05:58.661486+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
2020-09-16T14:05:58.661487+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
2020-09-16T14:05:58.661487+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
2020-09-16T14:05:58.661487+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
2020-09-16T14:05:58.661488+00:00 app[web.1]: [a6d3c433-2e99-478e-8deb-88fc530dd146] vendor/bundle/ruby/2.6.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by NicholasCF** [comment]
A temporary workaround for now if someone needs to reset their password is to send a reset request with their email, then retrieve the message from the logs
